name = "workart-dev"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
vars = { CLIENT_ORIGIN_URL = "http://localhost:3002" }
kv_namespaces = [
	 { binding = "MY_KV", preview_id = "1e623bf51b2442d782d61234079c67e6", id = "f47bddb3fd61448187157edf550b7d46" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"

[env.production]
name = "workart"
vars = { ENVIRONMENT = "production", CLIENT_ORIGIN_URL = "https://workart.pages.dev" }
kv_namespaces = [
  { binding = "MY_KV", id = "f47bddb3fd61448187157edf550b7d46" }
]
